language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget git swig libasound2-dev python-alsaaudio vlc-nox libpulse-dev

install:
  - pip install -r src/requirements.txt
  - pip install fakeRPiGPIO
  - pip install git+https://github.com/oaubert/python-vlc.git
  - pip install pylint
  - cp src/config.template.yaml src/config.yaml

script: 
  - pylint --errors-only --extension-pkg-whitelist=alsaaudio src/main.py
  - pylint --errors-only --extension-pkg-whitelist=alsaaudio src/alexapi
  - pylint --errors-only src/auth_web.py
